site_name: My site
site_url: https://thatguy9358.github.io/OSCP-Notes
theme:
  name: material
  palette:
    scheme: slate
    primary: light green
  features:
    - header.autohide
  logo: assets/logo2.png
use_directory_urls: false
markdown_extensions:
  - attr_list
plugins:
  - mkdocs-pdf
